#!/usr/bin/env zsh

############################################################# 
# nb-ad-dump-hash
#############################################################
nb-ad-dump-hash-help() {
    cat << "DOC" | bat --plain --language=help

nb-ad-dump-hash
------------
The nb-ad-dump-hash namespace contains commands for pass-the-hash attack on Active Directory DC server.

Commands
--------
nb-ad-dump-hash-install         installs dependencies

DOC
}

nb-ad-dump-hash-install() {
    __info "Running $0..."
    __pkgs crackmapexec
}

